# Use a Node.js image to build the app
ARG NODE_VERSION
FROM node:${NODE_VERSION} as build

WORKDIR /app

COPY .env.production .env
COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Use an Nginx image to serve the built app
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
