version: '3.8'

services:
  frontend:
    container_name: koala_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    stdin_open: true
    tty: true
  
  backend:
    container_name: koala_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - mongo

  mongo:
    container_name: koala_mongo
    image: mongo:${MONGO_VERSION}
    ports:
      - "${MONGO_PORT}:27017"